platform:
  - x64
  - ia32

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 8
  - npm install

build_script:
  - npm run windows

test: off
