platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 8 x64
  - npm install

build_script:
  - npm run release

test: off

environment:
  GH_TOKEN:
    secure: 56f475bbc0341858c2e1e1ec5eda9619cec523aa
